#!/bin/bash

apps_requirements() {
    # Homebrew is required.
    if test ! $(which brew); then
        return 1;
    fi

    return 0;
}

apps_install() {

    # Install Cask
    brew install caskroom/cask/brew-cask
    brew tap caskroom/versions

    # Development tool casks
    brew cask install --appdir="/Applications" macdown

    # Misc casks
    brew cask install --appdir="/Applications" 1password
    brew cask install --appdir="/Applications" google-chrome
    brew cask install --appdir="/Applications" firefox
    brew cask install --appdir="/Applications" skype
    brew cask install --appdir="/Applications" vlc
    
    # Remove outdated versions from the cellar.
    brew cleanup    
}
