#!/bin/bash

homebrew_requirements() {
    # Ruby is required.
    if test ! $(which ruby); then
        return 1;
    fi

    return 0;
}

homebrew_install() {
    if test ! $(which brew); then
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi    

    # Make sure we’re using the latest Homebrew.
    brew update

    # Upgrade any already-installed formulae.
    brew upgrade --all

    # Ask for the administrator password upfront
    sudo -v

    # Install GNU core utilities (those that come with OS X are outdated).
    # Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
    # brew install coreutils
    # sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

    # Install some other useful utilities like `sponge`.
    brew install moreutils
    # Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed.
    brew install findutils
    # Install GNU `sed`, overwriting the built-in `sed`.
    brew install gnu-sed --with-default-names
    # Install Bash 4.
    brew install bash
    brew tap homebrew/versions
    brew install bash-completion2
    # We installed the new shell, now we have to activate it
    echo "Adding the newly installed shell to the list of allowed shells"
    # Prompts for password
    sudo bash -c 'echo /usr/local/bin/bash >> /etc/shells'
    # Change to the new shell, prompts for password
    chsh -s /usr/local/bin/bash

    # Install `wget` with IRI support.
    brew install wget --with-iri    

    # Install more recent versions of some OS X tools.
    brew install vim --with-override-system-vi  
    
    # Install font tools.
    brew tap bramstein/webfonttools
    brew install sfnt2woff
    brew install sfnt2woff-zopfli
    brew install woff2

    # Install other useful binaries.
    brew install ack
    brew install dark-mode
    brew install git
    brew install git-lfs
    brew install git-flow
    brew install git-extras      

    # Install Cask
    #brew install caskroom/cask/brew-cask
    brew tap caskroom/versions
}
