#!/bin/bash

quicklook_requirements() {
    # Homebrew is required.
    if test ! $(which brew); then
        return 1;
    fi

    return 0;
}

quicklook_install() {

    # Install Cask
    brew install caskroom/cask/brew-cask
    brew tap caskroom/versions

    # Install developer friendly quick look plugins; see https://github.com/sindresorhus/quick-look-plugins
    brew cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv betterzipql qlimagesize webpquicklook suspicious-package
        
    # Remove outdated versions from the cellar.
    brew cleanup    
}
