#!/bin/bash

vscode_requirements() {
    # Homebrew is required.
    if test ! $(which brew); then
        return 1;
    fi

    return 0;
}

vscode_install() {

    # Install Cask
    brew tap caskroom/versions

    # Install macdown
    brew cask install --appdir="~/Applications" visual-studio-code

    # Remove outdated versions from the cellar.
    brew cleanup
}

